from __future__ import annotations

import importlib.util
import re
from pathlib import Path
from xml.etree import ElementTree as ET

import pytest


ROOT = Path(__file__).resolve().parents[1]
MRT = ROOT / "powerfactory" / "MASTER_GRIDLENS.mrt"
SCRIPT = ROOT / "powerfactory" / "gridlens_report.py"
SPEC = importlib.util.spec_from_file_location("gridlens_report_mrt", SCRIPT)
gl = importlib.util.module_from_spec(SPEC)
assert SPEC.loader is not None
SPEC.loader.exec_module(gl)


def _root():
    return ET.parse(MRT).getroot()


def _data_sources(root):
    sources = {}
    container = root.find(".//DataSources")
    assert container is not None
    for source in list(container):
        columns = source.find("Columns")
        assert columns is not None
        parsed = []
        for value in columns.findall("value"):
            name, dotnet_type = (value.text or "").split(",", 1)
            kind = {
                "System.String": "string",
                "System.Int32": "integer",
                "System.Double": "number",
            }[dotnet_type]
            parsed.append((name, kind))
        sources[source.tag] = tuple(parsed)
    return sources


def test_mrt_data_sources_exactly_match_python_contract():
    assert _data_sources(_root()) == dict(gl.TABLES)


def test_mrt_structure_and_release_invariants():
    root = _root()
    refs = [element.attrib["Ref"] for element in root.iter() if "Ref" in element.attrib]
    reference_targets = [element.attrib["isRef"] for element in root.iter()
                         if "isRef" in element.attrib]
    assert len(refs) == len(set(refs))
    assert set(reference_targets) <= set(refs) | {"0"}
    report_file = root.find("ReportFile")
    assert report_file is not None and not (report_file.text or "").strip()
    plots_chart = root.find(".//PlotsChart")
    assert plots_chart is not None
    assert len(plots_chart.findall("Style")) == 1
    assert root.findall(".//ImageBytes")
    assert root.findall(".//Bookmark")


def test_mrt_has_generated_by_run_mode_and_readable_qa_layout():
    root = _root()
    texts = {element.text for element in root.findall(".//Text")}
    assert "{ScriptedReportMeta.generated_by}" in texts
    assert "{ScriptedReportMeta.run_mode}" in texts
    assert "Generated by" in texts
    assert "Run mode" in texts
    assert "Model Quality Assurance" in texts
    assert "Planned Outages" in texts
    assert "Calculated Cases" in texts

    status_header = root.find(".//ModelQualityHeaderCell1")
    status_cell = root.find(".//ModelQualityCell1")
    details_cell = root.find(".//ModelQualityCell2")
    assert status_header is not None and status_cell is not None
    assert status_header.findtext("HorAlignment") == "Center"
    assert status_cell.findtext("HorAlignment") == "Center"
    assert "Bold" in (status_cell.findtext("Font") or "")
    assert details_cell is not None
    assert details_cell.findtext("ClientRectangle") == "6.2,0,7.5,0.55"


def test_mrt_contains_no_local_paths_or_obsolete_sources():
    text = MRT.read_text(encoding="utf-8")
    forbidden = (
        "/Users/", "/home/", "file://", "C:\\", "C:/",
        "ScriptedScenarios", "ScriptedOutages", "ScriptedScenario",
        "scenario_id", "scenario_name",
    )
    assert not [value for value in forbidden if value in text]


def test_visible_report_text_is_english():
    root = _root()
    visible = "\n".join(
        element.text or "" for element in root.findall(".//Text")
        if "{" not in (element.text or ""))
    german = re.compile(
        r"\b(Szenario|Studie|Auslastung|Spannung|Zeitpunkt|Ergebnis|"
        r"Grenzwert|Modell|Untersuchung|Referenz|Leitung|Transformator|"
        r"Knoten|Einheit|Beschreibung|Erstellt|Außerbetriebnahme)\b",
        re.IGNORECASE,
    )
    assert german.search(visible) is None


def _outage_cells(root):
    header, body = {}, {}
    for element in root.iter():
        if element.tag.startswith("OutagesHeaderCell"):
            header[element.tag] = element
        elif element.tag.startswith("OutagesCell"):
            body[element.tag] = element
    return header, body


def test_outage_table_reads_as_an_assessment_not_a_log():
    header, body = _outage_cells(_root())

    headings = [header["OutagesHeaderCell{}".format(i)].findtext("Text")
                for i in range(len(header))]
    assert headings == ["Planned outage", "Period", "Prio",
                        "Equipment out of service", "Assessment",
                        "Worst values inside the window"]

    texts = " ".join(body["OutagesCell{}".format(i)].findtext("Text")
                     for i in range(len(body)))
    for field in ("outage_name", "start_time", "end_time", "priority",
                  "equipment_name", "assessment", "assessment_detail"):
        assert "{ScriptedPlannedOutages.%s}" % field in texts
    # Internal bookkeeping must not take up column space any more.
    assert "source_class" not in texts
    assert "switching_actions" not in texts


def test_outage_columns_fill_the_page_width_exactly():
    header, body = _outage_cells(_root())

    for cells in (header, body):
        widths = []
        edge = 0.0
        for index in range(len(cells)):
            name = ("OutagesHeaderCell{}" if cells is header else "OutagesCell{}")
            rectangle = cells[name.format(index)].findtext("ClientRectangle")
            left, _, width, _ = (float(value) for value in rectangle.split(","))
            assert left == pytest.approx(edge), "column {} leaves a gap".format(index)
            edge += width
            widths.append(width)
        assert sum(widths) == pytest.approx(17.0)


def test_violations_are_highlighted_in_the_outage_table():
    _, body = _outage_cells(_root())

    flagged = []
    for name, cell in body.items():
        conditions = cell.find("Conditions")
        for condition in conditions.findall("value"):
            assert condition.text.startswith(
                "ScriptedPlannedOutages.violation,GreaterThan,")
            flagged.append(name)
    assert sorted(flagged) == ["OutagesCell4", "OutagesCell5"]
