"""Vertrag der 18 Report-Tabellen. Muss zu MASTER_GRIDLENS.mrt passen."""

FIELD_TYPES = {"string": 0, "integer": 1, "number": 2}

TABLES = (
    ("ScriptedReportMeta", (
        ("study_id", "string"), ("study_name", "string"),
        ("study_description", "string"), ("model_name", "string"),
        ("model_version", "string"), ("simulation_start", "string"),
        ("simulation_end", "string"), ("simulation_time_step", "string"),
        ("generation_date", "string"), ("template_name", "string"),
        ("template_version", "string"), ("data_contract_version", "string"),
        ("result_name", "string"), ("assessment_scope", "string"),
        ("assessment_status", "string"),
    )),
    ("ScriptedModelQuality", (
        ("check_id", "string"), ("check_name", "string"),
        ("status", "string"), ("message", "string"),
        ("affected_element", "string"),
    )),
    ("ScriptedScenarios", (
        ("scenario_id", "string"), ("scenario_name", "string"),
        ("is_reference", "integer"), ("description", "string"),
        ("simulation_status", "string"), ("simulation_start", "string"),
        ("simulation_end", "string"),
    )),
    ("ScriptedOutages", (
        ("scenario_id", "string"), ("outage_id", "string"),
        ("element_id", "string"), ("element_name", "string"),
        ("element_type", "string"), ("start_time", "string"),
        ("end_time", "string"), ("action", "string"),
    )),
    ("ScriptedScenarioMatrix", (
        ("element_id", "string"), ("element_name", "string"),
        ("element_type", "string"), ("scenario_id", "string"),
        ("is_out_of_service", "integer"), ("status_label", "string"),
    )),
    ("ScriptedLineStatistics", (
        ("scenario_id", "string"), ("element_id", "string"),
        ("element_name", "string"), ("voltage_level", "string"),
        ("min_loading", "number"), ("max_loading", "number"),
        ("mean_loading", "number"), ("p95_loading", "number"),
        ("time_of_min_loading", "string"),
        ("time_of_max_loading", "string"),
        ("reference_max_loading", "number"),
        ("delta_max_loading", "number"),
    )),
    ("ScriptedTransformerStatistics", (
        ("scenario_id", "string"), ("element_id", "string"),
        ("element_name", "string"), ("voltage_level", "string"),
        ("min_loading", "number"), ("max_loading", "number"),
        ("mean_loading", "number"), ("p95_loading", "number"),
        ("time_of_max_loading", "string"),
        ("reference_max_loading", "number"),
        ("delta_max_loading", "number"),
    )),
    ("ScriptedVoltageStatistics", (
        ("scenario_id", "string"), ("element_id", "string"),
        ("element_name", "string"), ("voltage_level", "string"),
        ("min_voltage", "number"), ("max_voltage", "number"),
        ("mean_voltage", "number"), ("time_of_min_voltage", "string"),
        ("time_of_max_voltage", "string"),
        ("reference_min_voltage", "number"),
        ("reference_max_voltage", "number"),
        ("delta_min_voltage", "number"), ("delta_max_voltage", "number"),
    )),
    ("ScriptedLineLoadingBars", (
        ("rank", "integer"), ("scenario_id", "string"),
        ("element_id", "string"), ("element_name", "string"),
        ("bar_label", "string"),
        ("voltage_level", "string"), ("max_loading", "number"),
        ("unit", "string"), ("event_time", "string"),
    )),
    ("ScriptedTransformerLoadingBars", (
        ("rank", "integer"), ("scenario_id", "string"),
        ("element_id", "string"), ("element_name", "string"),
        ("bar_label", "string"),
        ("voltage_level", "string"), ("max_loading", "number"),
        ("unit", "string"), ("event_time", "string"),
    )),
    ("ScriptedVoltageMagnitudeBars", (
        ("rank", "integer"), ("scenario_id", "string"),
        ("element_id", "string"), ("element_name", "string"),
        ("bar_label", "string"),
        ("voltage_level", "string"), ("min_voltage", "number"),
        ("max_voltage", "number"), ("mean_voltage", "number"),
        ("deviation", "number"), ("status_label", "string"),
        ("unit", "string"),
    )),
    ("ScriptedVoltageAngleBars", (
        ("rank", "integer"), ("scenario_id", "string"),
        ("element_id", "string"), ("element_name", "string"),
        ("bar_label", "string"),
        ("voltage_level", "string"), ("min_angle", "number"),
        ("max_angle", "number"), ("mean_angle", "number"),
        ("max_abs_angle", "number"), ("angle_span", "number"),
        ("event_time", "string"), ("unit", "string"),
    )),
    ("ScriptedReferenceComparison", (
        ("scenario_id", "string"), ("element_id", "string"),
        ("element_name", "string"), ("element_type", "string"),
        ("variable", "string"), ("unit", "string"),
        ("reference_min", "number"), ("scenario_min", "number"),
        ("delta_min", "number"), ("reference_max", "number"),
        ("scenario_max", "number"), ("delta_max", "number"),
        ("reference_mean", "number"), ("scenario_mean", "number"),
        ("delta_mean", "number"),
    )),
    ("ScriptedScenarioComparison", (
        ("metric_key", "string"), ("metric_name", "string"),
        ("unit", "string"), ("scenario_id", "string"),
        ("metric_value", "number"), ("element_id", "string"),
        ("element_name", "string"),
    )),
    ("ScriptedRankings", (
        ("ranking_type", "string"), ("rank", "integer"),
        ("scenario_id", "string"), ("element_id", "string"),
        ("element_name", "string"), ("element_type", "string"),
        ("metric_name", "string"), ("metric_value", "number"),
        ("unit", "string"), ("reference_value", "number"),
        ("delta_value", "number"), ("event_time", "string"),
    )),
    ("ScriptedRelevantTimePoints", (
        ("timestamp", "string"), ("scenario_id", "string"),
        ("reason", "string"), ("element_id", "string"),
        ("element_name", "string"), ("metric_name", "string"),
        ("metric_value", "number"), ("unit", "string"),
    )),
    ("ScriptedPlots", (
        ("plot_id", "string"), ("plot_title", "string"),
        ("scenario_id", "string"), ("element_id", "string"),
        ("element_name", "string"), ("variable", "string"),
        ("unit", "string"),
    )),
    ("ScriptedPlotData", (
        ("plot_id", "string"), ("scenario_id", "string"),
        ("series_role", "string"), ("timestamp", "number"),
        ("value", "number"),
    )),
)

